[workspace]
resolver = "2"
members = [
  "dotme-core",
  "dotme-test"
]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["matzxrr"]
description = "A git based dotfile manager"
documentation = "tbd"
