[workspace]
resolver = "2"
members = [
  "dotme-cli",
  "dotme-core",
  "dotme-test"
]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["matzxrr"]
description = "A git based dotfile manager"
documentation = "tbd"

[workspace.dependencies]
git2 = "0.18.1"
directories = "5.0.1"
